<?php
if (!defined('ABSPATH')) {
    exit;
}

abstract class WP_AI_Audit_Rule {
    /**
     * Permanent unique rule identifier (e.g. SEO_001, CONTENT_001, MEDIA_001)
     * @return string
     */
    abstract public function get_id();

    /**
     * Human-readable rule title
     * @return string
     */
    abstract public function get_title();

    /**
     * Audit category identifier
     * (seo_metadata | content_quality | media_accessibility | technical_structure | taxonomies_internal_links)
     * @return string
     */
    abstract public function get_category();

    /**
     * Default severity level for findings generated by this rule (critical | warning | info)
     * @return string
     */
    abstract public function get_severity();

    /**
     * Why this check matters for search performance or content accessibility
     * @return string
     */
    abstract public function get_rationale();

    /**
     * Actionable remediation guidance
     * @return string
     */
    abstract public function get_remediation();

    /**
     * Deterministically evaluate rule against gathered inventory data context
     * Must return array of WP_AI_Audit_Finding objects (or empty array if passed).
     * Rule classes MUST NOT calculate scores or assign deduction points.
     *
     * @param array $context Raw verified inventory data (pages, posts, media, acf, SEO meta)
     * @return WP_AI_Audit_Finding[]
     */
    abstract public function evaluate(array $context);
}
